config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # read (all)
  get 'pets', to: 'pets#index'

  # create
  get 'pets/new', to: 'pets#new', as: :new_pet
  post 'pets', to: 'pets#create'

  # read (one)
  get 'pets/:id', to: 'pets#show', as: :pet

  # update
  get 'pets/:id/edit', to: 'pets#edit', as: :edit_pet
  patch 'pets/:id', to: 'pets#update'

  # delete
  delete 'pets/:id', to: 'pets#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :species, inclusion: { in: %w(dog cat fish budgies) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :species, :address, :found_on)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%# <%= form_with model: @pet do |f| %>
<%# <%= f.label :name %>
<%# <%= f.text_field :name %>
<%# <%= f.label :species %>
<%# <%= f.text_field :species %>
<%# <%= f.label :address %>
<%# <%= f.text_field :address %>
<%# <%= f.label :found_on %>
<%# <%= f.date_field :found_on %>
<%# <%= f.submit %>
<%# <% end %>

<%# now we have the simple_form gem added we can use the below
for our form rather than form_with %>

<%= simple_form_for(pet) do |f| %>
  <%= f.input :name %>
  <%= f.input :species %>
  <%= f.input :address %>
  <%= f.input :found_on %>
  <%= f.submit %>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %></h1>

<%# using the form in the _form.html.erb partial %>
<%= render 'form', pet: @pet  %>

app/views/pets/index.html.erb
<h1>Lost pets</h1>
<ul>
  <% @pets.each do |pet| %>
    <li>
      <p>name: <%= pet.name %></p>
      <p>species: <%= pet.species %></p>
      <p>found_on: <%= pet.found_on %></p>
      <p>
        <%= link_to "read more on #{pet.name}", pet_path(pet) %>
      </p>
      <p>
        <%= link_to "remove #{pet.name}?", pet_path(pet), data: { turbo_method: :delete, turbo_confirm: "are you sure?" } %>
      </p>
    </li>
  <% end %>
</ul>

<p><%= link_to "add a new pet", new_pet_path %></p>

app/views/pets/new.html.erb
<h1>add a new pet here</h1>

<%# we no longer display the form inside the new.
Instead it is inside the _form.html.erb file
we now render the form using the line of code below,
passing the @pet instance we created in the new action
through to the partial.
%>
<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<p><%= @pet.species %></p>
<p><%= @pet.found_on %></p>
<%= link_to "edit #{@pet.name}", edit_pet_path(@pet) %>